//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarcodeHistory
    {
        public int BarcodeHistoryID { get; set; }
        public Nullable<int> CopyID { get; set; }
        public string GeneratedBarcode { get; set; }
        public Nullable<System.DateTime> GeneratedAt { get; set; }
        public Nullable<int> UniversityID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual MaterialCopy MaterialCopy { get; set; }
        public virtual MaterialCopy MaterialCopy1 { get; set; }
        public virtual tblSchool tblSchool { get; set; }
    }
}
