//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookinglisted
    {
        public int BookingID { get; set; }
        public int PatronID { get; set; }
        public int MaterialID { get; set; }
        public System.DateTime BookingDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> HoldExpiryDate { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Patron Patron { get; set; }
    }
}
