//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItem
    {
        public int CartItemID { get; set; }
        public int PatronID { get; set; }
        public int MaterialID { get; set; }
        public System.DateTime AddedAt { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Patron Patron { get; set; }
    }
}
