//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cataloguing
    {
        public int CataloguingID { get; set; }
        public int MaterialID { get; set; }
        public string MARCField { get; set; }
        public string MARCData { get; set; }
        public Nullable<int> UniversityID { get; set; }
    
        public virtual Material Material { get; set; }
    }
}
