//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Circulation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Circulation()
        {
            this.FineDetails = new HashSet<FineDetail>();
        }
    
        public int CirculationID { get; set; }
        public Nullable<int> CopyID { get; set; }
        public Nullable<int> PatronID { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> FineAmount { get; set; }
        public Nullable<int> UniversityID { get; set; }
        public Nullable<int> RequestID { get; set; }
        public Nullable<int> MaterialID { get; set; }
        public virtual IssuanceRequest IssuanceRequest { get; set; }

        public virtual MaterialCopy MaterialCopy { get; set; }
        public virtual Patron Patron { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FineDetail> FineDetails { get; set; }
    }
}
