//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Circulation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Circulation()
        {
            this.FineDetails = new HashSet<FineDetail>();
            this.FineDetails1 = new HashSet<FineDetail>();
        }
    
        public int CirculationID { get; set; }
        public Nullable<int> CopyID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> FineAmount { get; set; }
        public string UniversityID { get; set; }
        public Nullable<int> MaterialID { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public string BarcodeNumber { get; set; }
        public Nullable<bool> IsOverdue { get; set; }
        public Nullable<System.DateTime> LastFineUpdateDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public bool IsActive { get; set; }
        public string IssuedBy { get; set; }
        public Nullable<int> CounterID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FineDetail> FineDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FineDetail> FineDetails1 { get; set; }
        public virtual Material Material { get; set; }
        public virtual MaterialCopy MaterialCopy { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
