//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FineReason
    {
        public int FineReasonID { get; set; }
        public string Reason { get; set; }
        public decimal FineAmount { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public bool IsActive { get; set; }
        public string UserID { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
