//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FineDetail
    {
        public int FineID { get; set; }
        public Nullable<int> CirculationID { get; set; }
        public Nullable<int> PatronID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> AppliedDate { get; set; }
        public Nullable<bool> Paid { get; set; }
        public string UniversityID { get; set; }
        public string LibraryCategoryID { get; set; }
    
        public virtual Circulation Circulation { get; set; }
        public virtual Circulation Circulation1 { get; set; }
        public virtual Patron Patron { get; set; }
        public virtual Patron Patron1 { get; set; }
        public object Material { get; internal set; }
    }
}
