//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssuanceRequest
    {
        public int RequestID { get; set; }
        public int PatronID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> UniversityID { get; set; }
    
        public virtual Patron Patron { get; set; }
    }
}
