//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Librarian
    {
        public int LibrarianID { get; set; }
        public Nullable<int> LibraryCategoryID { get; set; }
        public string UserID { get; set; }
        public string EmailID { get; set; }
        public string UniversityID { get; set; }
        public string Name { get; set; }
        public string ContactNumber { get; set; }
    
        public virtual Librarian Librarians1 { get; set; }
        public virtual Librarian Librarian1 { get; set; }
        public virtual tblUniversity tblUniversity { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
