//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibraryCounter
    {
        public int CounterID { get; set; }
        public string CounterNumber { get; set; }
        public string CounterName { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string AssignedBy { get; set; }
        public int UniversityID { get; set; }
        public int SchoolID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
