//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.Cataloguings = new HashSet<Cataloguing>();
            this.MaterialCopies = new HashSet<MaterialCopy>();
            this.Reservations = new HashSet<Reservation>();
            this.CartItems = new HashSet<CartItem>();
        }
    
        public int MaterialID { get; set; }
        public Nullable<int> UniversityID { get; set; }
        public string Title { get; set; }
        public string Publisher { get; set; }
        public Nullable<int> YearPublished { get; set; }
        public string ISBN { get; set; }
        public string MaterialType { get; set; }
        public Nullable<int> AvailableQuantity { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public string Edition { get; set; }
        public string PlaceofPublishers { get; set; }
        public string Discription { get; set; }
        public Nullable<int> Pages { get; set; }
        public string Vol { get; set; }
        public string Source { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Author Author { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cataloguing> Cataloguings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialCopy> MaterialCopies { get; set; }
        public virtual University University { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartItem> CartItems { get; set; }
    }
}
