//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialCopy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaterialCopy()
        {
            this.BarcodeHistories = new HashSet<BarcodeHistory>();
            this.BarcodeHistories1 = new HashSet<BarcodeHistory>();
            this.Circulations = new HashSet<Circulation>();
        }
    
        public int CopyID { get; set; }
        public Nullable<int> MaterialID { get; set; }
        public string AccountNumber { get; set; }
        public string BarcodeNumber { get; set; }
        public string CallNumber { get; set; }
        public string Status { get; set; }
        public string UniversityID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsPrinted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BarcodeHistory> BarcodeHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BarcodeHistory> BarcodeHistories1 { get; set; }
        public virtual Material Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Circulation> Circulations { get; set; }
    }
}
