//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMangement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ICFAISMSEntities : DbContext
    {
        public ICFAISMSEntities()
            : base("name=ICFAISMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblUniversity> tblUniversities { get; set; }
        public virtual DbSet<tblUserRole> tblUserRoles { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblUserUniversity> tblUserUniversities { get; set; }
        public virtual DbSet<tblRole> tblRoles { get; set; }
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<BarcodeHistory> BarcodeHistories { get; set; }
        public virtual DbSet<FineDetail> FineDetails { get; set; }
        public virtual DbSet<FineReason> FineReasons { get; set; }
        public virtual DbSet<MaterialType> MaterialTypes { get; set; }
        public virtual DbSet<Librarycatgeory> Librarycatgeories { get; set; }
        public virtual DbSet<MaterialCopy> MaterialCopies { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<Circulation> Circulations { get; set; }
        public virtual DbSet<Bookinglisted> Bookinglisteds { get; set; }
        public virtual DbSet<Patron> Patrons { get; set; }
        public virtual DbSet<Librarian> Librarians { get; set; }
    }
}
