//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMangement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LMSEntities : DbContext
    {
        public LMSEntities()
            : base("name=LMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BarcodeHistory> BarcodeHistories { get; set; }
        public virtual DbSet<FineDetail> FineDetails { get; set; }
        public virtual DbSet<Librarian> Librarians { get; set; }
        public virtual DbSet<MaterialCopy> MaterialCopies { get; set; }
        public virtual DbSet<Patron> Patrons { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<University> Universities { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Cataloguing> Cataloguings { get; set; }
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<CartItem> CartItems { get; set; }
        public virtual DbSet<IssuanceRequest> IssuanceRequests { get; set; }
        public virtual DbSet<Circulation> Circulations { get; set; }
    }
}
