//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatronNewMaterialRequest
    {
        public int RequestID { get; set; }
        public string UserID { get; set; }
        public int SchoolID { get; set; }
        public int UniversityID { get; set; }
        public string MaterialTitle { get; set; }
        public string Author { get; set; }
        public string Edition { get; set; }
        public string Notes { get; set; }
        public System.DateTime RequestedDate { get; set; }
        public string Status { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
