//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patron
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patron()
        {
            this.Bookinglisteds = new HashSet<Bookinglisted>();
            this.Circulations = new HashSet<Circulation>();
            this.Circulations1 = new HashSet<Circulation>();
            this.FineDetails = new HashSet<FineDetail>();
            this.FineDetails1 = new HashSet<FineDetail>();
            this.PatronNewMaterialRequests = new HashSet<PatronNewMaterialRequest>();
        }
    
        public int PatronID { get; set; }
        public string UniversityID { get; set; }
        public string PatronName { get; set; }
        public string PatronEmail { get; set; }
        public string PatronPhone { get; set; }
        public string PatronType { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UserID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookinglisted> Bookinglisteds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Circulation> Circulations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Circulation> Circulations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FineDetail> FineDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FineDetail> FineDetails1 { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatronNewMaterialRequest> PatronNewMaterialRequests { get; set; }
    }
}
