//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssistantRequest
    {
        public int RequestID { get; set; }
        public string LibrarianUserID { get; set; }
        public string AssistantUserID { get; set; }
        public int LibraryID { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string UniversityID { get; set; }
    
        public virtual tblUniversity tblUniversity { get; set; }
    }
}
