//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int EmployeeID { get; set; }
        public string UserID { get; set; }
        public string EmployeeCode { get; set; }
        public string Title { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string EmergencyContactName { get; set; }
        public string EmergencyContactPhone { get; set; }
        public string Qualifications { get; set; }
        public string Experience { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedIPAddress { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedIPAddress { get; set; }
        public byte[] RowVersion { get; set; }
        public string PhotoPath { get; set; }
        public string Email { get; set; }
        public string MobileNumber { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public bool IsTeachingStaff { get; set; }
        public string FacultyType { get; set; }
        public string UniversityID { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblDesignation tblDesignation { get; set; }
    }
}
