//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSchool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSchool()
        {
            this.BarcodeHistories = new HashSet<BarcodeHistory>();
            this.tblUserSchools = new HashSet<tblUserSchool>();
            this.tblStudents = new HashSet<tblStudent>();
        }
    
        public int SchoolID { get; set; }
        public string SchoolName { get; set; }
        public string ShortName { get; set; }
        public string UniversityID { get; set; }
        public string HODUserID { get; set; }
        public string DepartmentEmail { get; set; }
        public string DepartmentPhone { get; set; }
        public string OfficeLocation { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedIPAddress { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedIPAddress { get; set; }
        public byte[] RowVersion { get; set; }
        public short Grading { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BarcodeHistory> BarcodeHistories { get; set; }
        public virtual tblUniversity tblUniversity { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserSchool> tblUserSchools { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudent> tblStudents { get; set; }
    }
}
