//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent
    {
        public string StudentID { get; set; }
        public string UserID { get; set; }
        public string EnrollmentNumber { get; set; }
        public string StudentName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string MobileNumber { get; set; }
        public string PersonalEmail { get; set; }
        public string ProfilePicture { get; set; }
        public string Course { get; set; }
        public Nullable<int> BatchYear { get; set; }
        public Nullable<int> CurrentSemester { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public string StudentStatus { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> ProgramInstanceID { get; set; }
        public Nullable<int> ProgramMasterID { get; set; }
        public Nullable<int> BatchID { get; set; }
        public string RegistrationSessionID { get; set; }
        public string VerificationStatus { get; set; }
        public Nullable<System.DateTime> VerifiedAt { get; set; }
        public string RegistrationSource { get; set; }
        public string IPAddressAtRegistration { get; set; }
        public string DeviceFingerprintAtRegistration { get; set; }
        public Nullable<System.DateTime> RegistrationCompletedAt { get; set; }
        public string DataHash { get; set; }
        public Nullable<int> EncryptionKeyVersion { get; set; }
        public string DisplayName { get; set; }
        public string PlaceOfBirth { get; set; }
        public string MaritalStatus { get; set; }
        public string Religion { get; set; }
        public string Caste { get; set; }
        public string Category { get; set; }
        public string Nationality { get; set; }
        public string StateOfOrigin { get; set; }
        public string MotherTongue { get; set; }
        public string Languages { get; set; }
        public bool PhysicallyChallenged { get; set; }
        public string DisabilityType { get; set; }
        public Nullable<decimal> DisabilityPercentage { get; set; }
        public string AcademicEmail { get; set; }
        public string AlternateMobile { get; set; }
        public string HomePhone { get; set; }
        public string WhatsAppNumber { get; set; }
        public string AadhaarNumber { get; set; }
        public string PANNumber { get; set; }
        public string PassportNumber { get; set; }
        public string DrivingLicense { get; set; }
        public string VoterID { get; set; }
        public string Hobbies { get; set; }
        public string SpecialSkills { get; set; }
        public string PersonalStatement { get; set; }
        public string SubmissionSessionID { get; set; }
        public Nullable<System.DateTime> SubmittedAt { get; set; }
        public string CreatedIPAddress { get; set; }
        public string ModifiedIPAddress { get; set; }
        public string ApplicationNumber { get; set; }
        public string AdmissionName { get; set; }
        public string UniversityID { get; set; }
        public string UniversityName { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public string ApprovalStatus { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string Gender { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<bool> domicile { get; set; }
    
        public virtual tblSchool tblSchool { get; set; }
        public virtual tblStudent tblStudent1 { get; set; }
        public virtual tblStudent tblStudent2 { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
