//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUniversity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUniversity()
        {
            this.tblRoles = new HashSet<tblRole>();
            this.tblSchools = new HashSet<tblSchool>();
            this.tblUserRoles = new HashSet<tblUserRole>();
            this.tblUserRoles1 = new HashSet<tblUserRole>();
            this.tblUserUniversities = new HashSet<tblUserUniversity>();
            this.tblUserSchools = new HashSet<tblUserSchool>();
        }
    
        public string UniversityID { get; set; }
        public string UniversityName { get; set; }
        public string ShortName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string ContactEmail { get; set; }
        public string ContactPhone { get; set; }
        public string AlternatePhone { get; set; }
        public string Website { get; set; }
        public string Logo { get; set; }
        public string Favicon { get; set; }
        public Nullable<int> UniversityTypeID { get; set; }
        public Nullable<int> EstablishedYear { get; set; }
        public string Affiliation { get; set; }
        public string AccreditationInfo { get; set; }
        public string CustomConfiguration { get; set; }
        public Nullable<int> MenuTemplateID { get; set; }
        public Nullable<int> RoleTemplateID { get; set; }
        public string ThemeConfiguration { get; set; }
        public string TimeZone { get; set; }
        public string Language { get; set; }
        public string Currency { get; set; }
        public string AcademicCalendar { get; set; }
        public bool IsActive { get; set; }
        public bool IsVerified { get; set; }
        public Nullable<System.DateTime> VerificationDate { get; set; }
        public string VerifiedBy { get; set; }
        public string LicenseType { get; set; }
        public Nullable<System.DateTime> LicenseExpiryDate { get; set; }
        public Nullable<int> MaxStudents { get; set; }
        public Nullable<int> MaxFaculty { get; set; }
        public Nullable<int> MaxStaff { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedIPAddress { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedIPAddress { get; set; }
        public byte[] RowVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRole> tblRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSchool> tblSchools { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserRole> tblUserRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserRole> tblUserRoles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserUniversity> tblUserUniversities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserSchool> tblUserSchools { get; set; }
    }
}
