//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserUniversity
    {
        public int UserUniversityID { get; set; }
        public string UserID { get; set; }
        public string UniversityID { get; set; }
        public Nullable<int> RoleHierarchyLevel { get; set; }
        public bool IsPrimary { get; set; }
        public bool CanManageUsers { get; set; }
        public bool SystemWideAccess { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public string Status { get; set; }
        public string ApprovalStatus { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tblUniversity tblUniversity { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
