//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorManagement
    {
        public int VisitorID { get; set; }
        public string VisitorName { get; set; }
        public string Purpose { get; set; }
        public string ContactNumber { get; set; }
        public System.DateTime VisitDate { get; set; }
        public string CreatedBy { get; set; }
        public string UniversityID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<System.DateTime> InTime { get; set; }
        public Nullable<System.DateTime> OutTime { get; set; }
    }
}
